### ISSUE TITLE
What a beautiful Name it is - Hillsong 

### ISSUE THREAD

**Issue by Ctasds** [mcruncher/worshipsongs-db-dev#246]
Hello, would really appreciate if you could help to add this song from Hillsong. Thank you for adding the other songs so far. 

The youtube for this song in Tamil - https://youtu.be/1z4s_sRvg3s

Song title - What a beautiful Name it is 
Writer - Ben Fielding, Brooke Ligertwood, Hillsong

**Verse 1**
You were the Word at the beginning 
One With God the Lord Most High                  
Your hidden glory in creation
Now revealed in You Our Christ 

**Chorus 1**
What a beautiful Name it is, What a beautiful Name it is, 
The Name of Jesus Christ my King
What a beautiful Name it is, Nothing compares to this
What a beautiful Name it is, The Name of Jesus

**Verse 2** 
You didn't want heaven without us              
So Jesus You brought heaven Down
My sin was great, Your love was greater                  
What could seperate us now 

**Chorus 2**
What a wonderful Name it is, What a wonderful Name it is
The Name of Jesus Christ my King
What a wonderful Name it is, Nothing compares to this
What a wonderful Name it is, The Name of Jesus
What a wonderful Name it is, The Name of Jesus

**Bridge**
Death could not hold you, The veil tore before You          
You silenced the boast of sin and grave 
The heavens are roaring, the praise of Your glory               
For you are raised to life again 
              
You have no rival, You have no equal                  
Now and forever God You reign 
Yours is the Kingdom, Yours is the glory                
Yours is the Name above all names 

**Chorus 3**
What a powerful Name it is, What a powerful Name it is
The Name of Jesus Christ my King
What a powerful Name it is, Nothing can stand against
What a powerful Name it is, The Name of Jesus
What a powerful Name it is, The Name of Jesus

**Tamil Verse 1**
Athiyile varthai neere
Unnatha thevan neere
Um Padaipinil kaana um mahimai
Kristhuvil indru naam kandom

**Tamil Chorus 1**
Ithu alahiya naamame, Ithu alahiya naamame 
Yesu Raja naamam menmaye
Ithu alahiya namame, Eedu inaiyilaye
Ithu alahiya namame, Yesuvin Naamam

**Tamil Verse 2**
Parathile paavi enai serka
Parane enakai vantheere
En Paawam parkilum um anpu periyathu
Ethuvum emmai pirikkathe

**Tamil Chorus 2**
Ithu arputha naamam, Ithu arputha naamam
Yesu Raja naamam menmaye
Ithu arputha naamam, Eedu inaiyilaye
Ithu arputha naamam, Yesuvin Naamam
Ithu arputha naamam, Yesuvin Naamam

**Tamil Bridge**
Maranathai jeyitheer, Thirai seelayai kilitheer
Pavarthei valei Neer mudiyethir
Paralogam mulangum, Um thuthi Papadum
En thevane uyirtheluntheer

Ummai pola yaruum, Yengumea illai
Indum endrum Neereh Raja 
Rajjiyam umathea, Maggimai umathea
Ella naamathilum Melanavar 

**Tamil Chorus 3**
Ithu vallamayin naamame﻿, Ithu vallamayin naamame﻿
Yesu Raja naamam menmaye
Ithu vallamayin naamame﻿, Eedu inaiyilaye
Ithu vallamayin naamame﻿, Yesuvin Naamam
Ithu vallamayin naamame﻿, Yesuvin Naamam

**Comment by Jancy2523** [comment]
[What a beautiful Name it is (Hillsong  Worship).zip](https://github.com/mcruncher/worshipsongs-db-dev/files/2037609/What.a.beautiful.Name.it.is.Hillsong.Worship.zip)

**Comment by Ctasds** [comment]
Is this song added to the app? I can't find the song even I've updated the songs.

**Comment by Jancy2523** [comment]
Hi,

We haven't added this song to our app. Will add soon.

**Comment by Jancy2523** [comment]
[Aathiyile Varthai Neere (Author Unknown {ஆசிரியர் தெரியவில்லை}).zip](https://github.com/mcruncher/worshipsongs-db-dev/files/2186651/Aathiyile.Varthai.Neere.Author.Unknown.zip)
