### ISSUE TITLE
New song to add - Change my heart O God

### ISSUE THREAD

**Issue by Ctasds** [mcruncher/worshipsongs-db-dev#249]
Change my heart Oh God

**Verse**
Change my heart oh God
Make it ever true 
Change my heart oh God
May I be like You 

**Chorus**
You are the potter
I am the clay
Mold me and make me 
This is what I pray 

Lyrics in tamil as below:

**Verse**
En ullathai maatrum
Muzhudhum maatrum
En ullathai maatrum
Ummai pol aakkum

**Chorus**
Neerae en kuyavan
Naan Kazhi mann
Vanaindhu kollum
Ummai polavey

https://www.youtube.com/watch?v=ckLOpBANT_4

**Comment by sskjames** [comment]
This song has been added in #250.
