### ISSUE TITLE
New request - August 2018

### ISSUE THREAD

**Issue by Ctasds** [mcruncher/worshipsongs-db-dev#251]
Dear all, 
Would appreciate your help to add these songs. 
God bless!

[Songs - Aug 2018.docx](https://github.com/mcruncher/worshipsongs-db-dev/files/2273893/Songs.-.Aug.2018.docx)

Thanks,
Seetha

**Comment by Jancy2523** [comment]
Thanks, 
We will add these songs.

**Comment by Jancy2523** [comment]
[God so Loved (Hillsong  Worship).zip](https://github.com/mcruncher/worshipsongs-db-dev/files/2326165/God.so.Loved.Hillsong.Worship.zip)
[Shout for joy, Hallelujah (Author Unknown {ஆசிரியர் தெரியவில்லை}).zip](https://github.com/mcruncher/worshipsongs-db-dev/files/2326166/Shout.for.joy.Hallelujah.Author.Unknown.zip)
