### ISSUE TITLE
New songs add - October

### ISSUE THREAD

**Issue by Ctasds** [mcruncher/worshipsongs-db-dev#255]
Greetings! Need your help to add these songs when possible. Regular songs we sing in our church and home fellowship. Thank you for your ministry. 
[New songs - Oct.docx](https://github.com/mcruncher/worshipsongs-db-dev/files/2471312/New.songs.-.Oct.docx)

**Comment by sskjames** [comment]
Thanks @Ctasds

**Comment by Jancy2523** [comment]
[Hosanna, Hosanna (Hillsong  Worship).zip](https://github.com/mcruncher/worshipsongs-db-dev/files/2471610/Hosanna.Hosanna.Hillsong.Worship.zip)

**Comment by Jancy2523** [comment]
[Lord I'm amazed by You (Author Unknown).zip](https://github.com/mcruncher/worshipsongs-db-dev/files/2471651/Lord.I.m.amazed.by.You.Author.Unknown.zip)

**Comment by Jancy2523** [comment]
[Jesus be the centre (Author Unknown {ஆசிரியர் தெரியவில்லை}).zip](https://github.com/mcruncher/worshipsongs-db-dev/files/2471660/Jesus.be.the.centre.Author.Unknown.zip)

**Comment by Jancy2523** [comment]
[Lift up your eyes (Author Unknown {ஆசிரியர் தெரியவில்லை}).zip](https://github.com/mcruncher/worshipsongs-db-dev/files/2471668/Lift.up.your.eyes.Author.Unknown.zip)

**Comment by Jancy2523** [comment]
[Holy is the Lord God Almighty (Chris Tomlin {கிறிஸ் டாம்லின்}).zip](https://github.com/mcruncher/worshipsongs-db-dev/files/2471682/Holy.is.the.Lord.God.Almighty.Chris.Tomlin.zip)

**Comment by Jancy2523** [comment]
[Jesus at the center (Darlene  Zschech).zip](https://github.com/mcruncher/worshipsongs-db-dev/files/2471685/Jesus.at.the.center.Darlene.Zschech.zip)

**Comment by Jancy2523** [comment]
[Forever Reign (Hillsong  Worship).zip](https://github.com/mcruncher/worshipsongs-db-dev/files/2471691/Forever.Reign.Hillsong.Worship.zip)

**Comment by Jancy2523** [comment]
[Broken Vessels (Amazing Grace) (Hillsong  Worship).zip](https://github.com/mcruncher/worshipsongs-db-dev/files/2471702/Broken.Vessels.Amazing.Grace.Hillsong.Worship.zip)
