### ISSUE TITLE
Add TMC SJ Congregation songs for June

### ISSUE THREAD

**Issue by sskjames** [mcruncher/worshipsongs-db-dev#265]
![WhatsApp Image 2019-05-13 at 9 40 23 AM](https://user-images.githubusercontent.com/229993/57597581-82131e00-7582-11e9-88eb-ddec57428377.jpeg)

**Comment by Jancy2523** [comment]
[Anaathi Thevan Un Adaikkalamae (Saral Navoriji {சாராள் நவரோஜி}).zip](https://github.com/mcruncher/worshipsongs-db-dev/files/3175463/Anaathi.Thevan.Un.Adaikkalamae.Saral.Navoriji.zip)
[Enna En Aanantham (Author Unknown {ஆசிரியர் தெரியவில்லை}).zip](https://github.com/mcruncher/worshipsongs-db-dev/files/3175464/Enna.En.Aanantham.Author.Unknown.zip)
[Guide Me O Thou Great Jehovah (William  Williams).zip](https://github.com/mcruncher/worshipsongs-db-dev/files/3175465/Guide.Me.O.Thou.Great.Jehovah.William.Williams.zip)
[Nearer, my God, to Thee (Sarah Flower).zip](https://github.com/mcruncher/worshipsongs-db-dev/files/3175466/Nearer.my.God.to.Thee.Sarah.Flower.zip)
[O For a Thousand Tongues (Charles Wesley).zip](https://github.com/mcruncher/worshipsongs-db-dev/files/3175467/O.For.a.Thousand.Tongues.Charles.Wesley.zip)
[Parisuthar Koottam Naduvil (Emil Jebasingh {எமில் ஜெபசிங்}).zip](https://github.com/mcruncher/worshipsongs-db-dev/files/3175468/Parisuthar.Koottam.Naduvil.Emil.Jebasingh.zip)
[Savior, like a shepherd lead us (Dorothy  A. Thrupp).xml.zip](https://github.com/mcruncher/worshipsongs-db-dev/files/3175469/Savior.like.a.shepherd.lead.us.Dorothy.A.Thrupp.xml.zip)
[Thaen Inimaiyilum (FMPB {நண்பர் சுவிசேஷ ஜெபக்குழு}).zip](https://github.com/mcruncher/worshipsongs-db-dev/files/3175470/Thaen.Inimaiyilum.FMPB.zip)
[Um Paatham Paninthaen (FMPB {நண்பர் சுவிசேஷ ஜெபக்குழு}).zip](https://github.com/mcruncher/worshipsongs-db-dev/files/3175471/Um.Paatham.Paninthaen.FMPB.zip)
[What a Friend we Have in Jesus (Joseph  Medlicott Scriven).zip](https://github.com/mcruncher/worshipsongs-db-dev/files/3175472/What.a.Friend.we.Have.in.Jesus.Joseph.Medlicott.Scriven.zip)
[Yaesuvai Poel Azhugullor (Author Unknown {ஆசிரியர் தெரியவில்லை}).zip](https://github.com/mcruncher/worshipsongs-db-dev/files/3175474/Yaesuvai.Poel.Azhugullor.Author.Unknown.zip)

**Comment by Jancy2523** [comment]
[Ratcha Paerumaanae Paarum (Dorothy  A. Thrupp).xml.zip](https://github.com/mcruncher/worshipsongs-db-dev/files/3221443/Ratcha.Paerumaanae.Paarum.Dorothy.A.Thrupp.xml.zip)
[Ummandai Kartharae (Sarah Flower).zip](https://github.com/mcruncher/worshipsongs-db-dev/files/3221444/Ummandai.Kartharae.Sarah.Flower.zip)

**Comment by Jancy2523** [comment]
1. Nearer my god thee- **Author : Sarah flower**
2. Umpatham panithaen - Already in the Database  **Author: FMPB**
3.  Saviour like a shepherd -  **Author: Dorothy A.Thrupp**
4. Thenin inimayilum -  Already in the Database **Author: FMPB**
5. Parisuthar kootam naduvil -  Already in the Database **Author :Emil Jebasingh**
6. Guide me o -  Already in the Database **Author:William williams**
7. Anathi devan -  Already in the Database **Author:Saral Navoriji**
8. What a friend we have -  Already in the Database **Author:Joseph Medicott Scriven**
9. Enaa en aanantham -  Already in the Database **Author:Unknown**
10. O for a thousand -  Already in the Database **Author:Charles Wesley**
11. Yaesuvaipol Allagulor -  **Author:Unknown**

**Comment by Jancy2523** [comment]
[Nearer, my God, to Thee (Sarah Flower).zip](https://github.com/mcruncher/worshipsongs-db-dev/files/3225216/Nearer.my.God.to.Thee.Sarah.Flower.zip)

**Comment by Jancy2523** [comment]
[Nearer, my God, to Thee (Sarah Flower).zip](https://github.com/mcruncher/worshipsongs-db-dev/files/3225232/Nearer.my.God.to.Thee.Sarah.Flower.zip)
[Savior, like a shepherd lead us (Dorothy  A. Thrupp).xml.zip](https://github.com/mcruncher/worshipsongs-db-dev/files/3225233/Savior.like.a.shepherd.lead.us.Dorothy.A.Thrupp.xml.zip)

**Comment by Jancy2523** [comment]
[Yaesuvai Poel Azhugullor (Author Unknown {ஆசிரியர் தெரியவில்லை}).zip](https://github.com/mcruncher/worshipsongs-db-dev/files/3225237/Yaesuvai.Poel.Azhugullor.Author.Unknown.zip)

**Comment by Jancy2523** [comment]
[Guide Me O Thou Great Jehovah (William  Williams).zip](https://github.com/mcruncher/worshipsongs-db-dev/files/3225263/Guide.Me.O.Thou.Great.Jehovah.William.Williams.zip)

**Comment by Jancy2523** [comment]
[What a Friend we Have in Jesus (Joseph  Medlicott Scriven).zip](https://github.com/mcruncher/worshipsongs-db-dev/files/3225282/What.a.Friend.we.Have.in.Jesus.Joseph.Medlicott.Scriven.zip)

**Comment by sskjames** [comment]
We need to add this song as well:

46 - Stand Up Stand Up for Jesus

**Comment by Jancy2523** [comment]
[O For a Thousand Tongues (Charles Wesley).zip](https://github.com/mcruncher/worshipsongs-db-dev/files/3230825/O.For.a.Thousand.Tongues.Charles.Wesley.zip)

**Comment by Jancy2523** [comment]
[Stand up, stand up for Jesus (George  Duffield).zip](https://github.com/mcruncher/worshipsongs-db-dev/files/3230870/Stand.up.stand.up.for.Jesus.George.Duffield.zip)
