### ISSUE TITLE
Add TMC SJ Congregation songs for July

### ISSUE THREAD

**Issue by Jancy2523** [mcruncher/worshipsongs-db-dev#267]
![July Month Songs](https://user-images.githubusercontent.com/13945334/59574939-d4001400-90eb-11e9-8a3e-3f00aa350f7a.PNG)

**Comment by Jancy2523** [comment]
1. All Hail the Power of Jesus
2. Unnatha Theiban unnai
3. Crown him with Many Crowns
4. Saruva Logathiba - Already in the database
5. Karthanae em Thunai -Already in the database
6. Saviuor like a shephered
7. En Kaalgaluku theebam 
8. Magilvom Magilvom -Already in the database
9. Rock of Ages
10. Thuthithu paadida paathiramae-

**Comment by Jancy2523** [comment]
1. All Hail the Power of Jesus - Updated the song with tamil lyrics
2. Unnatha Theiban unnai
3. Crown him with Many Crowns
4. Saruva Logathiba - Already in the database
5. Karthanae em Thunai -Already in the database
6. Saviuor like a shephered
7. En Kaalgaluku theebam 
8. Magilvom Magilvom -Already in the database
9. Rock of Ages
10. Thuthithu paadida paathiramae-

**Comment by Jancy2523** [comment]
[All Hail the Power of Jesus Name (Edward  Perronet).zip](https://github.com/mcruncher/worshipsongs-db-dev/files/3337156/All.Hail.the.Power.of.Jesus.Name.Edward.Perronet.zip)
[Unnatha Devan (Author Unknown {ஆசிரியர் தெரியவில்லை}).zip](https://github.com/mcruncher/worshipsongs-db-dev/files/3337157/Unnatha.Devan.Author.Unknown.zip)

**Comment by Jancy2523** [comment]
[Crown Him With Many Crowns (Author Unknown {ஆசிரியர் தெரியவில்லை}).zip](https://github.com/mcruncher/worshipsongs-db-dev/files/3353327/Crown.Him.With.Many.Crowns.Author.Unknown.zip)
[Devattuk Kuttiku Pan Mudi Suutidum (Author Unknown {ஆசிரியர் தெரியவில்லை}).zip](https://github.com/mcruncher/worshipsongs-db-dev/files/3353328/Devattuk.Kuttiku.Pan.Mudi.Suutidum.Author.Unknown.zip)

**Comment by Jancy2523** [comment]
[Savior, like a shepherd lead us (Dorothy  A. Thrupp).xml.zip](https://github.com/mcruncher/worshipsongs-db-dev/files/3353347/Savior.like.a.shepherd.lead.us.Dorothy.A.Thrupp.xml.zip)

**Comment by sskjames** [comment]
[Unnatha Thaevan Unnai Azhaikiraar (Author Unknown {ஆசிரியர் தெரியவில்லை})-edited.zip](https://github.com/mcruncher/worshipsongs-db-dev/files/3364559/Unnatha.Thaevan.Unnai.Azhaikiraar.Author.Unknown.-edited.zip)

**Comment by Jancy2523** [comment]
[En Kaalgalukku Theebam Yesu (Author Unknown {ஆசிரியர் தெரியவில்லை}).zip](https://github.com/mcruncher/worshipsongs-db-dev/files/3366361/En.Kaalgalukku.Theebam.Yesu.Author.Unknown.zip)

**Comment by Jancy2523** [comment]
[Crown Him With Many Crowns (Author Unknown {ஆசிரியர் தெரியவில்லை}).zip](https://github.com/mcruncher/worshipsongs-db-dev/files/3366721/Crown.Him.With.Many.Crowns.Author.Unknown.zip)

With Tamil and English lyrics

**Comment by Jancy2523** [comment]
[Rock of Ages (Author Unknown {ஆசிரியர் தெரியவில்லை}).zip](https://github.com/mcruncher/worshipsongs-db-dev/files/3366761/Rock.of.Ages.Author.Unknown.zip)

With Tamil and English lyrics

**Comment by Jancy2523** [comment]
[Thoothithu Paadida Paathiramae (FMPB {நண்பர் சுவிசேஷ ஜெபக்குழு}).zip](https://github.com/mcruncher/worshipsongs-db-dev/files/3366781/Thoothithu.Paadida.Paathiramae.FMPB.zip)

This song already in the database
I did some spelling mistakes in the lyrics
