### ISSUE TITLE
பெத்தலேகம் ஊரோரம் சத்திரத்தை

### ISSUE THREAD

**Issue by sskjames** [mcruncher/worshipsongs-db-dev#321]
Title: Bethlehem Ooroaram Sathirathai
Alternate title: Bethlegem Beththelegem Ororam Uroram
i18nTitle: பெத்தலேகம் ஊரோரம் சத்திரத்தை
Author: Author Unknown
Category: Keerthanaigal
Songbooks:
 - Geethangalum Keerthanaigalum (Song no: 105)
 
Lyrics: https://krishthavakeerthanaigal.blogspot.com/2018/12/blog-post_36.html

**Comment by Jancy2523** [comment]
Added
