### ISSUE TITLE
ஆர் இவர் ஆராரோ

### ISSUE THREAD

**Issue by sskjames** [mcruncher/worshipsongs-db-dev#322]
Title: Aar Ivar Aaraaroa
Alternate title: Ar Ivar Araro
i18nTitle: ஆர் இவர் ஆராரோ
Author: V. Masilamani Iyer (வே. மாசிலாமணி ஐயர்)
Category: Keerthanaigal
Songbooks:
  - Geethangalum Keerthanaigalum (Song no: 107)

Lyrics: https://krishthavakeerthanaigal.blogspot.com/2018/12/blog-post_69.html

**Comment by Jancy2523** [comment]
Added
