### ISSUE TITLE
ஆ அம்பர உம்பரமும் புகழுந்திரு

### ISSUE THREAD

**Issue by sskjames** [mcruncher/worshipsongs-db-dev#323]
Title: Aa Ambara Umbaramum Pugazhunthiru
Alternate title: A ambaram umbaram pugal
i18nTitle: ஆ அம்பர உம்பரமும் புகழுந்திரு
Author: Y. Yaakobu {யோ. யாக்கோபு}
Category: Keerthanaigal
Songbooks:
 - Geethangalum Keerthanaigalum (Song no: 108)
 
Lyrics: https://krishthavakeerthanaigal.blogspot.com/2018/12/blog-post_77.html

**Comment by Jancy2523** [comment]
Added
