### ISSUE TITLE
கண்டேனென் கண்குளிர

### ISSUE THREAD

**Issue by sskjames** [mcruncher/worshipsongs-db-dev#324]
Title: Kandaenen Kankulira
Alternate title: Kanden En Kankulira 
i18nTitle: கண்டேனென் கண்குளிர
Author: Author Unknown
Category: Keerthanaigal
Songbooks:
 - Geethangalum Keerthanaigalum (Song no: 110)
 
Lyrics: https://krishthavakeerthanaigal.blogspot.com/2018/12/blog-post_75.html

**Comment by Jancy2523** [comment]
Added
