### ISSUE TITLE
என்ன பாக்கியம் எவர்க்குண்டு

### ISSUE THREAD

**Issue by sskjames** [mcruncher/worshipsongs-db-dev#325]
Title: Enna Paakiyam Evarkkundu
Alternate title: Enna Baakiyam Enna Bakiyam Yenna Pakiam Bakyam Pakyam
i18nTitle: என்ன பாக்கியம் எவர்க்குண்டு
Author: Gabriel Ubathesiyaar (காபிரியேல் உபதேசியார்)
Category: Keerthanaigal
Songbooks:
 - Geethangalum Keerthanaigalum (Song no: 111)
 
Lyrics: https://krishthavakeerthanaigal.blogspot.com/2018/12/blog-post_47.html

**Comment by Jancy2523** [comment]
Added
