### ISSUE TITLE
ஆத்துமா கர்த்தரைத் துதிக்கின்றதே

### ISSUE THREAD

**Issue by sskjames** [mcruncher/worshipsongs-db-dev#326]
Title: Aathumaa Kartharai Thuthikindrathae
Alternate title: Aathuma Kartharai Athuma Kartharai
i18nTitle: ஆத்துமா கர்த்தரைத் துதிக்கின்றதே
Author: Gnanamani Iyer {ச.த. ஞானமணி ஐயர்}
Category: Keerthanaigal
Songbooks:
 - Geethangalum Keerthanaigalum (Song no: 116)
 
Lyrics: https://krishthavakeerthanaigal.blogspot.com/2018/12/blog-post_54.html

**Comment by Jancy2523** [comment]
Added
