### ISSUE TITLE
குருசினில் தொங்கியே

### ISSUE THREAD

**Issue by sskjames** [mcruncher/worshipsongs-db-dev#327]
Title: Kurusinil Thonggiyae
Alternate title: Kurusinil Thongiye 
i18nTitle: குருசினில் தொங்கியே
Author: Author Unknown
Category: Keerthanaigal
Songbooks:
 - Geethangalum Keerthanaigalum (Song no: 155)
 
Lyrics: https://krishthavakeerthanaigal.blogspot.com/2019/01/blog-post_66.html

**Comment by Jancy2523** [comment]
Added
