### ISSUE TITLE
எழுந்தார் இறைவன்

### ISSUE THREAD

**Issue by sskjames** [mcruncher/worshipsongs-db-dev#328]
Title: Ezhunthaar Iraivan
Alternate title: Elunthaar Iraivan Elundhaar Elundhar Elundar yiraivan
i18nTitle: எழுந்தார் இறைவன்
Author: S. Paramanantham Iyer {சா. பரமானந்தம் ஐயர்}
Category: Keerthanaigal
Songbooks:
 - Geethangalum Keerthanaigalum (Song no: 178)
 
Lyrics: https://krishthavakeerthanaigal.blogspot.com/2019/01/blog-post_68.html

**Comment by Jancy2523** [comment]
Added
