### ISSUE TITLE
இந்நாளில் ஏசுநாதர் உயிர்த்தார்

### ISSUE THREAD

**Issue by sskjames** [mcruncher/worshipsongs-db-dev#329]
Title: Innaalil Yeasu Naathar Uyirthaar
Alternate title: Innaalil Yesu Inalil Yesu Magizh Kondaaduvoam Magizh Kondaduvom Magil
i18nTitle: இந்நாளில் ஏசுநாதர் உயிர்த்தார்
Author: Author Unknown
Category: Keerthanaigal
Songbooks:
 - Geethangalum Keerthanaigalum (Song no: 179)
 
Lyrics: https://krishthavakeerthanaigal.blogspot.com/2019/01/blog-post_15.html

**Comment by Jancy2523** [comment]
Added
