### ISSUE TITLE
யூத ராஜ சிங்கம் உயிர்த்தெழுந்தார்

### ISSUE THREAD

**Issue by sskjames** [mcruncher/worshipsongs-db-dev#330]
Title: Yootha Raaja Singam Uyirthezhunthaar
Alternate title: Yoodha Raaja Yutha Raja Yudha Raja Yuda Raja
i18nTitle: யூத ராஜ சிங்கம் உயிர்த்தெழுந்தார்
Author: Author Unknown
Category: Keerthanaigal
Songbooks:
 - Geethangalum Keerthanaigalum (Song no: 180)
 
Lyrics: https://krishthavakeerthanaigal.blogspot.com/2019/05/blog-post_724.html

**Comment by Jancy2523** [comment]
Added
