### ISSUE TITLE
இயேசு நசரையி னதிபதியே

### ISSUE THREAD

**Issue by sskjames** [mcruncher/worshipsongs-db-dev#332]
Title: Yaesu Nasarayin Athipathiyae
Alternate title: Yesu Nasarayin Adhibadhiye
i18nTitle: இயேசு நசரையி னதிபதியே
Author: Savarimuthu Ubathiyayar {சவரிமுத்து உபாத்தியாயர்}
Category: Keerthanaigal
Songbooks:
 - Geethangalum Keerthanaigalum (Song no: 202)
 
Lyrics: https://krishthavakeerthanaigal.blogspot.com/2019/01/blog-post_3.html

**Comment by Jancy2523** [comment]
Added
