### ISSUE TITLE
சுந்தரப் பரம தேவ மைந்தன்

### ISSUE THREAD

**Issue by sskjames** [mcruncher/worshipsongs-db-dev#333]
Title: Sunthara Parama Thaeva Mainthan
Alternate title: Sundara Parama Deva Maindhan Sundhara
i18nTitle: சுந்தரப் பரம தேவ மைந்தன்
Author: Mariyan Ubathesiyar {மரியான் உபதேசியார்}
Category: Keerthanaigal
Songbooks:
 - Geethangalum Keerthanaigalum (Song no: 203)
 
Lyrics: https://krishthavakeerthanaigal.blogspot.com/2019/01/blog-post_26.html

**Comment by Jancy2523** [comment]
Added
