### ISSUE TITLE
ராச ராச பிதா மைந்த

### ISSUE THREAD

**Issue by sskjames** [mcruncher/worshipsongs-db-dev#334]
Title: Raasa Raasa Pithaa Maintha
Alternate title: Rasa Rasa Pidha Pidha
i18nTitle: ராச ராச பிதா மைந்த
Author: Vedhanayagam Sasthiriyar {வேதநாயகம் சாஸ்திரியார்}
Category: Keerthanaigal
Songbooks:
 - Geethangalum Keerthanaigalum (Song no: 206)
 
Lyrics: https://krishthavakeerthanaigal.blogspot.com/2018/12/blog-post_61.html

**Comment by Jancy2523** [comment]
Added
