### ISSUE TITLE
 வாரும் நாம் எல்லோரும் கூடி

### ISSUE THREAD

**Issue by sskjames** [mcruncher/worshipsongs-db-dev#335]
Title: Vaarum Naam Elloarum Koodi
Alternate title: Varum Nam Ellorum 
i18nTitle:  வாரும் நாம் எல்லோரும் கூடி
Author: Y. Palmer {யோ. பால்மர்}
Category: Keerthanaigal
Songbooks:
 - Geethangalum Keerthanaigalum (Song no: 215)
 
Lyrics: https://krishthavakeerthanaigal.blogspot.com/2019/04/blog-post_584.html

**Comment by Jancy2523** [comment]
Added
