### ISSUE TITLE
சேனைகளின் கர்த்தரே நின் திருவிலம்

### ISSUE THREAD

**Issue by sskjames** [mcruncher/worshipsongs-db-dev#336]
Title: Saenaigalin Kartharae Nin Thiruvilam
Alternate title: Senaigalin Karthare
i18nTitle: சேனைகளின் கர்த்தரே நின் திருவிலம்
Author: N. Samuel Iyer {ஞா. சாமுவேல் ஐயர்}
Category: Keerthanaigal
Songbooks:
 - Geethangalum Keerthanaigalum (Song no: 219)
 
Lyrics: https://krishthavakeerthanaigal.blogspot.com/2019/04/blog-post_64.html
Media url: https://www.youtube.com/watch?v=4BEpK6RTPaw

**Comment by Jancy2523** [comment]
Added
