### ISSUE TITLE
பயந்து கர்த்தரின் பக்தி வழியில்

### ISSUE THREAD

**Issue by sskjames** [mcruncher/worshipsongs-db-dev#342]
Title: Payanthu Kartharin Pakthi Vazhiyil
Alternate title: Payandhu Bayandhu Bayandu
i18nTitle:  பயந்து கர்த்தரின் பக்தி வழியில்
Author: Author Unknown
Category: Keerthanaigal
Songbooks:
 - Geethangalum Keerthanaigalum (Song no: 278)
 
Lyrics: https://tamilchristiansongs.org/lyrics/payanthu-karththarin-pakthi-valiyil/
Media url:

**Comment by Jancy2523** [comment]
Added
