### ISSUE TITLE
ஆவியை மழைபோலே யூற்றும்

### ISSUE THREAD

**Issue by sskjames** [mcruncher/worshipsongs-db-dev#343]
Title: Aaviyai Mazhaipoalae Ootrum
Alternate title: Aviyai Malaipola
i18nTitle:  ஆவியை மழைபோலே யூற்றும்
Author: Arulanantham Pirasangiyar {அருளானந்தம் பிரசங்கியார்}
Category: Keerthanaigal
Songbooks:
 - Geethangalum Keerthanaigalum (Song no: 309)
 
Lyrics: https://krishthavakeerthanaigal.blogspot.com/2019/01/blog-post_46.html
Media url:

**Comment by Jancy2523** [comment]
Added
