### ISSUE TITLE
 ஆவியை அருளுமே சுவாமீ

### ISSUE THREAD

**Issue by sskjames** [mcruncher/worshipsongs-db-dev#344]
Title: Aaviyai Arulumae Swaami
Alternate title: Aviyai Arulume
i18nTitle:  ஆவியை அருளுமே சுவாமீ
Author: Arulanantham Pirasangiyar {அருளானந்தம் பிரசங்கியார்}
Category: Keerthanaigal
Songbooks:
 - Geethangalum Keerthanaigalum (Song no: 310)
 
Lyrics: https://krishthavakeerthanaigal.blogspot.com/2019/01/blog-post_9.html
Media url:

**Comment by Jancy2523** [comment]
Added
