### ISSUE TITLE
ஐயையா நான் ஒரு மா பாவி

### ISSUE THREAD

**Issue by sskjames** [mcruncher/worshipsongs-db-dev#345]
Title: Aiyaiyaa Naan Oru Maa Paavi
Alternate title: Aiyaiya Iyyaya Iyaya Ayayah Ayyayya
i18nTitle:  ஐயையா நான் ஒரு மா பாவி
Author: P. Davethu Iyer {பா. தாவீது ஐயர்}
Category: Keerthanaigal
Songbooks:
 - Geethangalum Keerthanaigalum (Song no: 313)
 
Lyrics: https://krishthavakeerthanaigal.blogspot.com/2019/01/blog-post_81.html
Media url: https://www.youtube.com/watch?v=YZiA3ACaVUQ

**Comment by Jancy2523** [comment]
Added
