### ISSUE TITLE
பக்தருடன் பாடுவேன் பரம சபை

### ISSUE THREAD

**Issue by sskjames** [mcruncher/worshipsongs-db-dev#346]
Title: Paktharudan Paaduvaen Parama Sabai
Alternate title: Baktharudan Paaduven Paduven
i18nTitle:  பக்தருடன் பாடுவேன் பரம சபை
Author: Yesudasan Savarirayan {ஏசுதாசன் சவரிராயன்}
Category: Keerthanaigal
Songbooks:
 - Geethangalum Keerthanaigalum (Song no: 355)
 
Lyrics: https://krishthavakeerthanaigal.blogspot.com/2019/05/blog-post_19.html
Media url:

**Comment by Jancy2523** [comment]
Added
