### ISSUE TITLE
எங்கும் புகழ் யேசு ராசனுக்கே

### ISSUE THREAD

**Issue by sskjames** [mcruncher/worshipsongs-db-dev#347]
Title: Enggum Pugazh Yaesu Raasanukkae
Alternate title: Engum Pugal Yesu
i18nTitle: எங்கும் புகழ் யேசு ராசனுக்கே
Author: Author Unknown
Category: Keerthanaigal
Songbooks:
 - Geethangalum Keerthanaigalum (Song no: 388)
 
Lyrics: https://krishthavakeerthanaigal.blogspot.com/2019/05/blog-post_43.html
Media url:

**Comment by Jancy2523** [comment]
Added
