### ISSUE TITLE
காலத்தின் அருமையை அறிந்து வாழாவிடில்

### ISSUE THREAD

**Issue by sskjames** [mcruncher/worshipsongs-db-dev#350]
Title: Kaalathin Arumaiyai Arinthu Vaazhavidil
Alternate title: Kalathin Arumai Arumay
i18nTitle: காலத்தின் அருமையை அறிந்து வாழாவிடில்
Author: Author Unknown
Category: Keerthanaigal
Songbooks:
 - Geethangalum Keerthanaigalum (Song no: 424)
 
Lyrics: https://krishthavakeerthanaigal.blogspot.com/2019/01/blog-post_16.html
Media url:

**Comment by Jancy2523** [comment]
Added
