### ISSUE TITLE
இயேசு நாமம் ஒன்றை நம்புவீர்

### ISSUE THREAD

**Issue by sskjames** [mcruncher/worshipsongs-db-dev#351]
Title: Yaesu Naamam Ondrai Nambuveer
Alternate title: Yesu Namam
i18nTitle: இயேசு நாமம் ஒன்றை நம்புவீர்
Author: E.S. Pakianathan {ஈ.சா. பாக்கியநாதன்}
Category: Keerthanaigal
Songbooks:
 - Geethangalum Keerthanaigalum (Song no: 425)
 
Lyrics: https://krishthavakeerthanaigal.blogspot.com/2019/01/blog-post_50.html
Media url:

**Comment by Jancy2523** [comment]
Added
