### ISSUE TITLE
Oh Glory to God He has lifted me up

### ISSUE THREAD

**Issue by sskjames** [mcruncher/worshipsongs-db-dev#360]
[Oh Glory to God He has lifted me up (O Thaevanukku Magimai) (Author Unknown {ஆசிரியர் தெரியவில்லை}).xml.zip](https://github.com/mcruncher/worshipsongs-db-dev/files/7698437/Oh.Glory.to.God.He.has.lifted.me.up.O.Thaevanukku.Magimai.Author.Unknown.xml.zip)

**Comment by Jancy2523** [comment]
Added
