### ISSUE TITLE
He is the same unchanging Jesus

### ISSUE THREAD

**Issue by sskjames** [mcruncher/worshipsongs-db-dev#361]
[He is the same unchanging Jesus (Yaesu Kiristhu Maaraathavarae) (Author Unknown {ஆசிரியர் தெரியவில்லை}).xml.zip](https://github.com/mcruncher/worshipsongs-db-dev/files/7698427/He.is.the.same.unchanging.Jesus.Yaesu.Kiristhu.Maaraathavarae.Author.Unknown.xml.zip)

**Comment by Jancy2523** [comment]
Added
