### ISSUE TITLE
Aaraainthu Mudiyaatha Kaariyangal

### ISSUE THREAD

**Issue by sskjames** [mcruncher/worshipsongs-db-dev#362]
Title: Aaraainthu Mudiyaatha Kaariyangal
Alternate title: Aarainthu Aaraindhu Araainthu Arainthu
i18nTitle: ஆராய்ந்து முடியாத காரியங்கள்
Author: T.D. John Christopher
mediaUrl: https://www.youtube.com/watch?v=F5E1wzFPvp4 
Category: Praise {துதி}
Lyrics (given by our user):

*_ஆராய்ந்து முடியாத காரியங்கள்,_*
*_எண்ணி முடியாத அதிசயங்கள்,_ -(2)*
*_செய்தவரே செய்பவரே செய்து முடிப்பவரே_,-(2)*
            *- ஆராய்ந்து*

*1, கிரகிக்க முடியாத அற்புதங்கள்,*
*யோசிக்க முடியாத அதிசயங்கள்,-2*
*நீர் ஒருவரே எனக்காக யாவையும் செய்பவரே-(2) -அல்லேலூயா-3*
       *- ஆராய்ந்து*

*2, யோசனையில் நீர் பெரியவரே,*
*செயல்களிலே நீர் வல்லவரே,-2*
*நீர் ஒருவரே ஜெயத்தை எனக்கு தருபவரே- -அல்லேலூயா (-3)*
            *-ஆராய்ந்து*

*3, மனுஷனால் கூடாத காரியங்கள்,*
*தேவனால் எல்லாம் நடந்திடும்,-2*
*நீர் ஒருவரே அற்புதங்கள் எனக்காக செய்பவரே, -அல்லேலூயா-(3)*
            *-ஆராய்ந்து*

**Comment by Jancy2523** [comment]
Added
